---
version: 1
disable_existing_loggers: true

formatters:
  simple:
    format: "%(asctime)s.%(msecs)03d | %(levelname)8s | %(name)16s:%(lineno)-4d | %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S"
handlers:
  logfile:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: "t1dgrs2.log"
    maxBytes: 1048576
    backupCount: 5
    encoding: UTF-8
    level: DEBUG
loggers:
  t1dgrs2:
    level: DEBUG
    handlers: [logfile]
    propagate: no
root:
  level: DEBUG
  handlers: [logfile]
  propagate: yes
